# This file controls the settings for your Quarto template from www.marvinschmitt.com


# website settings
website:
  title: "Olanrewaju Yusuff"                                # Your name
  description: "I am a Ph.D. candidate in [Economics](https://aysps.gsu.edu/economics/) at [Georgia State University](https://www.gsu.edu/). My research focuses on Health Economics, Public Economics, and Development Economics, specializing in healthcare accessibility, utilization, and outcomes. My job market paper examines the health effects of access to mental health treatment facilities.
I previously worked as a Research Assistant at the [Centre for Econometrics and Applied Research (CEAR)](https://www.linkedin.com/company/centre-for-econometrics-and-applied-research/posts/?feedView=all) at the University of Ibadan."   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/my_image.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "CV"
        href: cv/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Contact"
        href: contact/index.qmd
     # - text: "Blog"
      #  href: blog/index.qmd
    
    # your social media handles
    right:
      - icon: google-scholar
        href: https://scholar.google.com/citations?user=eL92kpYAAAAJ&hl=en
      - icon: twitter
        href: https://x.com/olayusuff14
      - icon: github
        href: https://github.com/olanrewajuyusuffecon
      - icon: envelope
        aria-label: email
        href: "mailto:oyusuff4@student.gsu.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2025 Olanrewaju Yusuff</span>
    center: |
      <span class="faux-block">PhD Candidate in Economics | Georgia State University</span>
    right: |
      <span class="faux-block">On the Job Market 2025-2026</span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true
  resources:
    - img/

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true